{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgresql-secret
  labels:
    {{- include "discordbot.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.postgresql.auth.postgresPassword }}
  postgres-password: {{ .Values.postgresql.auth.postgresPassword | b64enc }}
  {{- else }}
  postgres-password: {{ randAlpha 32 | b64enc }}
  {{- end }}
{{- end }}