apiVersion: v1
entries:
  discordbot:
    - name: discordbot
      version: 0.1.0
      appVersion: 1.0.0
      kubeVersion: ">=1.24.0-0"
      description: A Helm chart for deploying the Discord Bot application
      type: application
      keywords:
        - discord
        - bot
        - django
        - discordjs
      maintainers:
        - name: MidhunKumar05
          email: midhun@example.com
      URLs:
        - https://midhunkumar05.github.io/charts/discordbot/
      created: 2026-04-23T00:00:00Z
      digest: sha256-placeholder
