apiVersion: v1
entries:
  discordbot:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2026-04-23T20:05:10.438154+10:00"
    description: A Helm chart for deploying the Discord Bot application
    digest: 70da25c6f003f613427593b81d619152c1cdc162b9caa8b4b8dc590ffff040de
    keywords:
    - discord
    - bot
    - django
    - discordjs
    maintainers:
    - email: midhun@example.com
      name: MidhunKumar05
    name: discordbot
    type: application
    urls:
    - https://midhunkumar05.github.io/charts/discordbot-0.1.1.tgz
    version: 0.1.1
generated: "2026-04-23T20:05:10.436888+10:00"
